# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Appium Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          jdk: '11'
          
      # Adding to resolve error
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platform: 'android-29'
          
#       - name: Set executable permissions for adb
#         run: chmod +x /path/to/adb
# till this

      - name: Set up Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: '29'
          emulator-version: '30.1.5'
          profile: 'Nexus 5'
        
      - name: Start Android emulator
        run: echo no | avdmanager create avd --force -n test -k "system-images;android-29;google_apis;x86"

      - name: Launch Android emulator
        run: $ANDROID_HOME/emulator/emulator -avd test -no-window -no-audio &

      - name: Wait for emulator to start
        run: android-wait-for-emulator
        
      - name: Run Maven commands
        run: |
          mvn clean install

      - name: Run tests
        run: |
          mvn test

#       - name: Set up Android emulator
#         uses: reactivecircus/android-emulator-runner@v2
#         with:
#           api-level: 29
#           target: default
#           architecture: x86
#           profile: Nexus 6
#           hw-options: hw.gpu.mode=auto

#       - name: Start emulator
#         run: emulator -avd Nexus6_API29 -no-audio -no-window &

#       - name: Wait for emulator to start
#         run: android-wait-for-emulator

#       - name: Build and test with Maven
#         run: mvn clean install -Pandroid

#       - name: Run Appium tests
#         run: mvn test

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         api-level: [29]
#         target: [default]
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up JDK 1.8
#       uses: actions/setup-java@v1
#       with:
#         java-version: '1.8'
#     - uses: actions/setup-node@v2
#       with:
#         node-version: '16'
#     - run : |
#             npm install -g appium@v1.20.2
#             appium -v
#             appium &>/dev/null &
#     - name: Run Appium Tests
#       uses: reactivecircus/android-emulator-runner@v2
#       with:
#         api-level: ${{ matrix.api-level }}
#         target: ${{ matrix.target }}
#         arch: x86_64
#         profile: Nexus 6
#         script: mvn test

# jobs:
#   test:
#     runs-on: macos-latest
#     steps:
#       - name: checkout
#         uses: actions/checkout@v3

#       - name: run tests
#         uses: reactivecircus/android-emulator-runner@v1
#         with:
#           api-level: 29
#           script: mvn clean test -Pandroid
